options(spinner.color="#0275D8", spinner.color.background="#ffffff", spinner.size=2)
library(leaflet)
library(ggplot2)
library(shiny)
library(htmltools)
library(leaflet)
library(shiny)
library(shinydashboard)
library(tidyr)
library(shinyjs)
library(shinydashboardPlus)
library(shinycssloaders)
library(plotly)
source("common_table.R")

